### ISSUE TITLE
 index 55 is out of bounds for axis 0 with size 55

### ISSUE THREAD

**Issue by peach2wanzi** [tomrunia/OpticalFlow_Visualization#2]
This is the issue When I run this code:
Traceback (most recent call last):
  File "ceshi.py", line 44, in <module>
    flow_color = flow_vis.flow_to_color(flow_uv, convert_to_bgr=False)
  File "/home/fang/OpticalFlow_Visualization-master/flow_vis.py", line 142, in flow_to_color
    return flow_compute_color(u, v, convert_to_bgr)
  File "/home/fang/OpticalFlow_Visualization-master/flow_vis.py", line 99, in flow_compute_color
    col0 = tmp[k0] / 255.0
IndexError: index 55 is out of bounds for axis 0 with size 55

Can somebody tell me What's wrong about it?

**Comment by dfrumkin** [comment]
The Matlab original has:
```
fk = (a+1) /2 * (ncols-1) + 1;  % -1~1 maped to 1~ncols
```
This +1 at the end is for Malab 1-based indexing - and it was preserved in the Python code:
```
fk = (a+1) / 2*(ncols-1) + 1
```
Looks like changing this to:
```
fk = (a+1) / 2*(ncols-1)
```
should help.

**Comment by dfrumkin** [comment]
Pull request #3
